{ 
  "error": 4, 
  "mensaje_error": "Ya existe un usuario con esas credenciales." 
}